export const INITIAL_ASSIGNMENT_COUNT = 40;
export const ADDITIONAL_ASSIGNMENT_COUNT = 10;
export const MAX_ASSIGNMENTS_PER_RATER = 100;
export const ASSIGNMENT_RANDOM_SEED = 42;
export const REQUIRED_REVIEWS_PER_QUERY = 3;
